language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
- pip install -U pytest pytest-cov
script:
 - python setup.py develop
 - pytest --cov=pocketcasts
env:
  global:
  - secure: QSZ9/hqK4H47a1TSxQ5Kvg4UTE1CEomiVL7wXuh7sEgLnzHKZqXd55pvQLROBdcQxtPskrudFLIyZ+r3z+oO2LosEwS6CMjE5uRhcDvaL4jtzxj/mK9GRcwo+O0QDnvsQcuN05thA48VBI/HHEI8+Lbiq3A5miHAymtEKBVaZsGiGP7SrIFyJinKlJzhrUmjICoyCOJz5qT9t++RwL7DLLsF3pPvR4as11ilCaiaxDCVQTRRqz9VeX9546QMJlizjXr5aZY7GNqIL4vvDMKlwp4qQFXriqiXG+ABVlVrGyYMXt5BqKaSYKLo/unc0fIZuXYFZTBclLYUkCMI5WjKYdp1trvTR6D/CRS8+/kuKL3uSEZswrdvp3jSQooWlv7aaUUbTatkfk+nBkpMrkk77j2xnXckQKit7qLnxMmWEL/7xBog97b9NFhDUzDK9D4+oa4tOT+Cjlb/sHakY+fzMoCG+S8AC0zuT19tV7lNuLkdRqgt6matWrNCTFS9PfT1pGVV0NwKdAaIK/1yEfYuiuoXRLpHrkEDpOAc1KNvGIFeW2m6QDE+YfjOwHltlSwBhtAWhjBcGSj1qfPl0n3pkL4OCJnKhDvOuaYNgfRW1mXMGF1vIibeRap7HPp8Hoo1dyWJrdpd0YBUfxb96/p7pKOHs58g31Nohn8kPAsy5dI=
  - secure: poMsAy7jkY3N7XiQn4l+fGHGNXGlQWUkFW232yZuP6NInfb2oGZ5qq2dTquZq1aReu7h1CYMGb35pbkmS60qW+9zEz4E0i1fTVW2WWRQshD1kdY4yMhUMWnriNHhxGlRTKLXeoT4anoUu+TmOGrlwJqxJQ27ACNKMAtEQzBqc++02ArwXOw86GmGjzsdtNbwtYIZMgNK0WqVFFRjChyc+6OWNo6vOmbESL8ZwKzGbK6Fr8PmyAJF8KSpzJ8wpI7L5DkZRTwxu6c1+kAFW8SvblbrazHrqk2T11jgBXCKEjCTIR7NJA2/1XgvK9qKhKKUhm8AynAnD3ae5xs/Vm9JM0isBfYQOwFe8h9p+KlNFytm5DAu7wxrD9O5yfGSPeflQwwYor2MJjk5+XX6OmYFwVs0Q/S6NVAhQMCwRINshhB0A/nYsaUlFruiFMhlgNAXi9VTt64DDVgdPz1cNSm3iZKCRC8NI0cfeudzzXhp5qxcJg5iYPzQgK2TKiu/tglFZAWdTFLrKxdX/dfRKQykUtYQjre8vwzgFR6P4PAzUBeHVojHrE2bf0EVO1GFBDYU6A7xkIZi0VY4CVFivzLWmlc830wTTz4KwhAL8tqyWJECLT1bceryOelEcrp95QupAIACv3iHkRNiU7qmaym7/JVtOdW/S1ruUpipjLxqHvM=
after_success:
  - coveralls