language: python
python:
- '3.3'
- '3.4'
- '3.5'
cache: pip
install:
- pip install -r requirements.txt
- pip install -U pytest
- python setup.py develop
script: pytest tests/tests.py
deploy:
  provider: pypi
  user: exofudge
  password:
    secure: ejFkRqUQ1ahfDcmF71xcBSgq2ZmTSgxDwdBb/3dHCiABVMn6RBMAKcx3uMO03Pxl4YlkphxndvHcVQSjZw0j30ZwEQqT52l8sj7/+HsbitZKl4DKmWgMOvAi6iyjs0YEcNFMsBUh4ZMlC27B9MyJ0Q5mfZFCU6+n5lFz6YrKVnSdcf585K22ulqTc7rF2rK1UjDjPRJ3QrLiaCPzmDzIiaU632JYYUbnbiycJ725mcozbCQS85QQZt3SgS2QF/0PAXEs2QxPreb7/JDHLjSoAW5uw69X/Osi3XX1X53tY8BXiIBhugQaGaAoDaNSac63fKMlml9srMNz9vCnDktH1qWBuuWNfkZxDMkI44XwYzxTpEkgEQDQoCZsSjHvXJJwfMDy7wiPH5rHwtKRTsfkoNa9di6zFJfccJbixOYr1zanIA5J7PftQwfrtwjMpgvi7uUTns7Xc/oEm2fsyr3Gvd6eGW+pXsC+1fBdqWvTAx7egMoYvr6h8KFeSRKo2axJ6QLZy4QfWIJY0eqzlsfHNlbjH+Hfd9UXhGOkgh8sECEb3RcFhNt6wWS930RnBPIC3/pV+Jqdqg9ZwLMl4q7+c5w0lLvJCIMbJutPTlOcS72yQihbb5FqztRJi7tiLT+hgDpnYeJMZJmqskuO9FcZ5Stb34BHrYl+Biw2HoXXOW8=
  on:
    tags: true
env:
  global:
  - secure: QSZ9/hqK4H47a1TSxQ5Kvg4UTE1CEomiVL7wXuh7sEgLnzHKZqXd55pvQLROBdcQxtPskrudFLIyZ+r3z+oO2LosEwS6CMjE5uRhcDvaL4jtzxj/mK9GRcwo+O0QDnvsQcuN05thA48VBI/HHEI8+Lbiq3A5miHAymtEKBVaZsGiGP7SrIFyJinKlJzhrUmjICoyCOJz5qT9t++RwL7DLLsF3pPvR4as11ilCaiaxDCVQTRRqz9VeX9546QMJlizjXr5aZY7GNqIL4vvDMKlwp4qQFXriqiXG+ABVlVrGyYMXt5BqKaSYKLo/unc0fIZuXYFZTBclLYUkCMI5WjKYdp1trvTR6D/CRS8+/kuKL3uSEZswrdvp3jSQooWlv7aaUUbTatkfk+nBkpMrkk77j2xnXckQKit7qLnxMmWEL/7xBog97b9NFhDUzDK9D4+oa4tOT+Cjlb/sHakY+fzMoCG+S8AC0zuT19tV7lNuLkdRqgt6matWrNCTFS9PfT1pGVV0NwKdAaIK/1yEfYuiuoXRLpHrkEDpOAc1KNvGIFeW2m6QDE+YfjOwHltlSwBhtAWhjBcGSj1qfPl0n3pkL4OCJnKhDvOuaYNgfRW1mXMGF1vIibeRap7HPp8Hoo1dyWJrdpd0YBUfxb96/p7pKOHs58g31Nohn8kPAsy5dI=
  - secure: poMsAy7jkY3N7XiQn4l+fGHGNXGlQWUkFW232yZuP6NInfb2oGZ5qq2dTquZq1aReu7h1CYMGb35pbkmS60qW+9zEz4E0i1fTVW2WWRQshD1kdY4yMhUMWnriNHhxGlRTKLXeoT4anoUu+TmOGrlwJqxJQ27ACNKMAtEQzBqc++02ArwXOw86GmGjzsdtNbwtYIZMgNK0WqVFFRjChyc+6OWNo6vOmbESL8ZwKzGbK6Fr8PmyAJF8KSpzJ8wpI7L5DkZRTwxu6c1+kAFW8SvblbrazHrqk2T11jgBXCKEjCTIR7NJA2/1XgvK9qKhKKUhm8AynAnD3ae5xs/Vm9JM0isBfYQOwFe8h9p+KlNFytm5DAu7wxrD9O5yfGSPeflQwwYor2MJjk5+XX6OmYFwVs0Q/S6NVAhQMCwRINshhB0A/nYsaUlFruiFMhlgNAXi9VTt64DDVgdPz1cNSm3iZKCRC8NI0cfeudzzXhp5qxcJg5iYPzQgK2TKiu/tglFZAWdTFLrKxdX/dfRKQykUtYQjre8vwzgFR6P4PAzUBeHVojHrE2bf0EVO1GFBDYU6A7xkIZi0VY4CVFivzLWmlc830wTTz4KwhAL8tqyWJECLT1bceryOelEcrp95QupAIACv3iHkRNiU7qmaym7/JVtOdW/S1ruUpipjLxqHvM=
